name: Application Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      opensilver-version:
        description: 'OpenSilver version to use'
        default: '1.2.1'
        required: true
      
jobs:
  BuildApp:
    runs-on: windows-latest
    steps:
      - name: Just print
        run: echo "Message from CI CD " ${{ github.event.inputs.opensilver-version }}
      - uses: microsoft/setup-msbuild@v1.1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.200'
      - name: Clone the repository
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Restore packages
        run: |
          nuget restore CICD_Demo.sln
      - name: Build
        run: |
          msbuild CICD_Demo.Browser\CICD_Demo.Browser.csproj
